### ISSUE TITLE
Problem when run python point_cloud_labeling.py

### ISSUE THREAD

**Issue by Mamba-ZJP** [XanX3601/point_cloud_labeling#5]
I met a problem when I run python point_cloud_labeling.py.
```
Traceback (most recent call last):
  File "point_cloud_labeling.py", line 126, in <module>
    out = model(torch.from_numpy(matrix).float())
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/point_cloud_labeling/utils/neural_net.py", line 42, in forward
    x = self.conv_0(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 587, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 583, in _conv_forward
    input, weight, bias, self.stride, self.padding, self.dilation, self.groups
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```

**Comment by Mamba-ZJP** [comment]
I find the solution: out = model(torch.from_numpy(matrix).float().to(device))
predicted_labels[neighbors_filter] = label.cpu().numpy()
